const products=[['Nova X Pro Smartphone','Mobiles',24999,'📱',4.6],['Aero Wireless Headphones','Electronics',2999,'🎧',4.4],['SmartFit AMOLED Watch','Electronics',4499,'⌚',4.5],['ProBook Air Laptop','Electronics',62990,'💻',4.7],['Urban Classic Sneakers','Fashion',1899,'👟',4.3],['Everyday Cotton Shirt','Fashion',899,'👕',4.2],['HomeBlend Mixer Grinder','Home',2499,'🍳',4.4],['CloudCool Air Cooler','Appliances',7999,'❄️',4.1],['Ergo Office Chair','Home',6499,'🪑',4.5],['Ultra HD Smart TV','Electronics',28990,'📺',4.6],['TravelPro Backpack','Travel',1299,'🎒',4.4],['FreshCare Skincare Set','Beauty',1599,'🧴',4.5]];
const cats=[['Mobiles','📱'],['Electronics','💻'],['Fashion','👕'],['Home','🏠'],['Appliances','⚡'],['Travel','🎒'],['Beauty','✨']];
let selected='All',cart=JSON.parse(localStorage.getItem('omcart')||'[]');const $=s=>document.querySelector(s),money=n=>'₹'+n.toLocaleString('en-IN');
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function buildCategories(){ $('#categoryList').innerHTML='<button class="cat-nav active" data-cat="All">All</button>'+cats.map(c=>`<button class="cat-nav" data-cat="${c[0]}">${c[1]} ${c[0]}</button>`).join(''); $('#categoryCards').innerHTML=cats.slice(0,6).map(c=>`<div class="category-card" data-cat="${c[0]}"><div class="category-icon">${c[1]}</div><b>${c[0]}</b></div>`).join(''); $('#filterCategories').innerHTML='<button class="filter-cat active" data-cat="All">All Categories</button>'+cats.map(c=>`<button class="filter-cat" data-cat="${c[0]}">${c[0]}</button>`).join('') }
function render(){const q=$('#searchInput').value.toLowerCase(),max=+$(`#maxPrice`).value;let list=products.map((p,i)=>({p,i})).filter(x=>(selected==='All'||x.p[1]===selected)&&x.p[2]<=max&&x.p[0].toLowerCase().includes(q));const s=$('#sortSelect').value;if(s==='low')list.sort((a,b)=>a.p[2]-b.p[2]);if(s==='high')list.sort((a,b)=>b.p[2]-a.p[2]);if(s==='rating')list.sort((a,b)=>b.p[4]-a.p[4]);$('#productGrid').innerHTML=list.length?list.map(x=>{const p=x.p;return `<article class="product"><span class="badge">${p[4]>=4.6?'Top Rated':'Deal'}</span><div class="product-image">${p[3]}</div><div class="product-body"><h3>${p[0]}</h3><div class="rating">★ ${p[4]} · ${p[1]}</div><div class="price">${money(p[2])}</div><button class="add-cart" data-id="${x.i}">Add to Cart</button></div></article>`}).join(''):'<div style="grid-column:1/-1;background:#fff;padding:50px;text-align:center">No products match your search.</div>'}
function cartUI(){const count=cart.reduce((a,x)=>a+x.q,0),total=cart.reduce((a,x)=>a+x.p[2]*x.q,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><div class="mini-img">${x.p[3]}</div><div><b>${x.p[0]}</b><small>${money(x.p[2])} × ${x.q}</small></div><div class="qty"><button data-minus="${x.i}">−</button><span>${x.q}</span><button data-plus="${x.i}">+</button></div></div>`).join(''):'<p style="text-align:center;color:#7a8491;margin-top:60px">Your cart is empty.</p>'}
function save(){localStorage.setItem('omcart',JSON.stringify(cart));cartUI()}function add(i){const x=cart.find(c=>c.i===i);x?x.q++:cart.push({i,p:products[i],q:1});save();toast(products[i][0]+' added to cart')}
function closePanels(){$('#cartDrawer').classList.remove('open');$('#loginModal').classList.remove('show');$('#overlay').classList.remove('show')}function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}
buildCategories();render();cartUI();
document.addEventListener('click',e=>{const c=e.target.closest('[data-cat]');if(c){selected=c.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('active',x.dataset.cat===selected));render();$('#shop').scrollIntoView({behavior:'smooth'})}const a=e.target.closest('[data-id]');if(a)add(+a.dataset.id);const plus=e.target.closest('[data-plus]');if(plus){cart.find(x=>x.i==plus.dataset.plus).q++;save()}const minus=e.target.closest('[data-minus]');if(minus){const x=cart.find(x=>x.i==minus.dataset.minus);x.q--;if(x.q<1)cart=cart.filter(y=>y.i!==x.i);save()}});
$('#searchForm').onsubmit=e=>{e.preventDefault();render();$('#shop').scrollIntoView({behavior:'smooth'})};$('#searchInput').oninput=render;$('#sortSelect').onchange=render;$('#maxPrice').oninput=()=>{$('#priceLabel').textContent='Up to '+money(+$(`#maxPrice`).value);render()};$('#clearFilters').onclick=()=>{selected='All';$('#searchInput').value='';$('#maxPrice').value=100000;$('#priceLabel').textContent='Up to ₹1,00,000';buildCategories();render()};$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closePanels;$('#overlay').onclick=closePanels;$('#loginBtn').onclick=()=>{$('#loginModal').classList.add('show');$('#overlay').classList.add('show')};$('#closeLogin').onclick=closePanels;$('#continueLogin').onclick=()=>{closePanels();toast('Demo login complete')};$('#checkoutBtn').onclick=()=>toast(cart.length?'Checkout demo — connect payment gateway':'Add a product first');document.querySelectorAll('[data-scroll-products]').forEach(b=>b.onclick=()=>$('#shop').scrollIntoView({behavior:'smooth'}));$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Thanks for subscribing!')};
let t=8*3600+45*60+32;setInterval(()=>{t=(t+86399)%86400;$('#dealTimer').textContent=[Math.floor(t/3600),Math.floor(t%3600/60),t%60].map(x=>String(x).padStart(2,'0')).join(' : ')},1000);
